export const routes = {
  home: "/",
  trackOrder: "/order/:orderNumberParam",
  signIn: "/fo-admin",
  adminPanel: "/admin-panel",
  products: "/admin-panel/products",
  productsRegister: "/admin-panel/products/new-product",
  productsEdit: "/admin-panel/products/edit-product/:id",
  company: "/admin-panel/company",
  neighborhoods: "/admin-panel/neighborhoods",
  media: "/admin-panel/media",
  schedule: "/admin-panel/schedule",
  shippingMessage: "/admin-panel/shipping-message",
  orders: "/admin-panel/orders",
  ordersHistory: "/admin-panel/orders-history",
  ordersHistoryEdit: "/admin-panel/orders-history/edit/:id",
  ordersHistoryRegister: "/admin-panel/orders-history/register",
  companyChatAi: "/admin-panel/company-chat-ai",
};
